name: CI/CD Deployment

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/it911-backend:$TAG ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/it911-backend:$TAG

      - name: Build and push frontend image
        run: |
          
          docker build \
            --no-cache \
            --build-arg ENV_FILE=$ENV_FILE \
            -t ${{ secrets.DOCKER_USERNAME }}/it911-frontend:$TAG \
            ./frontend

          docker push ${{ secrets.DOCKER_USERNAME }}/it911-frontend:$TAG

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ github.ref_name == 'main' && secrets.SERVER_HOST || secrets.SERVER_HOST_TEST }}
          username: ${{ github.ref_name == 'main' && secrets.SERVER_USER || secrets.SERVER_USER_TEST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/it911

            # выбираем docker-compose файл
            if [ "${{ github.ref_name }}" = "main" ]; then
              COMPOSE_FILE="docker-compose.yml"
            else
              COMPOSE_FILE="docker-compose.test.yml"
            fi

            git pull
            docker-compose -f $COMPOSE_FILE down
            docker-compose -f $COMPOSE_FILE pull
            docker-compose -f $COMPOSE_FILE up -d --build
            
